# comparer configuration demo

# log configuration
log_dir: "./tmp"
comparer_name: "comparer_demo"

# compare configuration
# compare mode:
# 0 : compare directory
# 1 : compare file
# 2 : compare filelist
compare_mode: 0

# file_type :
# 0 : pickle file
# 1 : protobuf file
file_type: 0

# ------- compare directory
compare_directory_options:
  # you can configure which epochs and steps to be compared
  # if compare_epochs or compare_steps is not set,
  # default compare all epochs or steps in the compared directory.
  # compare_epochs:
  #   - 0
  #   - 1
  # compare_steps:
  #   - 3
  #   - 4
  only_compare_forward: false
  only_compare_backward: false
  only_compare_input: false
  only_compare_output: false
  compared_directory_1: "/LocalRun/shaobo.xie/2_Pytorch/model/Yolo/yolov3/tmp/tracer_demo_backward_hook_1677062509"
  compared_directory_2: "/LocalRun/shaobo.xie/2_Pytorch/model/Yolo/yolov3/tmp/tracer_demo_backward_hook_1677062575"

# ------- compare file
# compare_file_options :
#   compared_file_1 : "xxxx"
#   compared_file_2 : "yyyy"

# ------- compare filelist
compare_filelist_options :
  compared_filelist_1 : "/LocalRun/shaobo.xie/2_Pytorch/model/Yolo/yolov3/tmp/tracer_demo_backward_hook_1675422052/epoch0/step0"
  compared_filelist_2 : "/LocalRun/shaobo.xie/2_Pytorch/model/Yolo/yolov3/tmp/tracer_demo_backward_hook_1675422052/epoch0/step1"
verbose: false

compare_by_order : true

# evaluation configuration
evaluation_metrics:
  - "CS"        # cosine similarity
  # - "MSE"       # mean squared error
  # - "RMSE"      # root mean squared error
  # - "MAPE"      # mean absolute percentage error
